apiVersion: v1
kind: Service
metadata:
  name: phi-4
  namespace: default
spec:
    selector:
      app: phi-4
    ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    type: ClusterIP
